config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  post 'user/create'

  post 'complaint/create'
  post 'complaint/complaints'

  root to: 'complaint#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/complaint.rb
class Complaint < ActiveRecord::Base
  belongs_to :user
  belongs_to :ministry
end

app/models/ministry.rb
class Ministry < ActiveRecord::Base
  has_many :complaints
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :complaints
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/complaint_controller.rb
class ComplaintController < ApplicationController
  def index
    @complaints = Complaint.all
  end
  def create
    @user = User.find_by_id(params[:user_id])
    if(@user == nil)
      return {"error" => "no_user_passed"}
    end
    if @user.complaints.create(:ministry_id => params[:ministry_id],:img_url=> params[:img_url] ,
                               :audio_text=> params[:audio_text], :video_url => params[:video_url],
                               :location => params[:location],:description => params[:description])
      render :create
    end
  end

  def status
    @user = User.find_by_id(params[:user_id])
    @complaint = @user.complaints.find_by_id(params[:complaint_id])
    render :status
  end

  def complaints
    @user = User.find_by_id(params[:user_id])
    @user_complaints = @user.complaints
    render :complaints
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def create
    @user = User.find_by_guest_id(params[:guest_id]) || User.create(:guest_id  => params[:guest_id])
    render :create
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/complaint_helper.rb
module ComplaintHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/complaint/index.html.erb
<table>
  <tr>
    <th>User_id</th>
    <th>_____</th>
    <th></th>
    <th>ministry</th>
    <th>_____</th>
    <th>image_link</th>
    <th>_____</th>
    <th>audio_link</th>
    <th>_____</th>
    <th>video_link</th>
    <th>location</th>
    <th>_____</th>
    <th>status</th>
    <th>_____</th>
    <th>time of creation</th>
  </tr>
  testinfgsjdlfndlfkafalksjfnaslkjfndakjsfaksjfbafhljfsbaslkj.
  <%@complaints.each do |complaint|%>

      <tr>
        <td>
          <%= complaint.user_id %>
        </td>
        <td>_____</td>

        <td>
          <%= Ministry.find_by_id(complaint.ministry_id) %>
        </td>
        <td>_____</td>
        <td>
          <%= complaint.img_url %>
        </td>
        <td>_____</td>

        <td><%= complaint.audio_text %></td>
        <td>_____</td>
        <td><%= complaint.video_url %></td>
        <td>_____</td>
        <td><%= complaint.location %></td>
        <td>_____</td>
        <td><%= complaint.status %></td>
        <td>_____</td>
        <td><%= complaint.created_at %></td>
        <td>_____</td>
      </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Public Grevance Control Panel</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header class="navbar navbar-default" role="navigation">
  <div class="navbar-inner">
    <div class="container">
      <div id="logo" class="navbar-brand"><%= link_to "Public Grevance Control Panel", root_path %></div>
      <nav class="collapse navbar-collapse navbar-ex1-collapse">
        <% if admin_signed_in? %>
            <ul class="nav navbar-nav navbar-right">

            </ul>
        <% else -%>
            <ul class="nav navbar-nav pull-right">
              <li><%= link_to 'Sign up', new_admin_registration_path %></li>
              <li><%= link_to 'Sign in', new_admin_session_path %></li>
            </ul>
        <% end -%>
      </nav>
    </div>
  </div>
</header>
<% if admin_signed_in? %>
    <div id="userEmail" >
      Signed in as <%= current_admin.email %>
    </div>
<% end %>

<div id="main_content" class="container">
  <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info") %>
  <% end %>

  <div id="content" class="col-md-9 center-block">
    <%= yield %>
  </div>
</div>
</div>
</body>
</html>

app/views/user/authenticate.html.erb
<h1>User#authenticate</h1>
<p>Find me in app/views/user/authenticate.html.erb</p>